baseURL = 'https://claudiakurtyka.github.io/'
languageCode = 'en-us'
title = "Claudia's website"
theme = 'claudia'



# If false, English tags like `Getting Started` will be converted to `getting-started
preserveTaxonomyNames = true
# Automatically detects if Chinese/Japanese/Korean is included, this parameter affects the summary and word count functions and is recommended to be set to true
hasCJKLanguage = false
enableGitInfo = true

# Pagination
paginate = 10
paginatePath = "page"

# enable Emoji; see emoji-cheat-sheet.com
enableEmoji = false


[permalinks]
  post = "/:year/:month/:title/"


[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]


[params]
  keywords = "blog,life,code,desgin"
  author = "claudia kurtyka"
  typed_names="UI/UX desginer"
  homepage = "homepage"
  copyright = "© Copyright 2023"
  email = "claudiakurtyka-design@gmail.com"
  avatar = "https://i.328888.xyz/2023/03/19/Pf8MH.png"
  description = "description here"
  aboutImage = "https://photo.tuchong.com/7194943/f/1141846321.jpg"
  [[params.social]]
      url   = "https://linkedin.com/"
      icon  = "fa-brands fa-linkedin fa-lg"
      name = "linkedin"
 [[params.social]]
      url   = "https://facebook.com/"
      icon  = "fa-brands fa-facebook fa-lg" 
      name = "facebook"

  [[params.social]]
      url = "https://linkedin.com/"  
      icon = "fa-brands fa-instagram fa-lg" 
      name = "instagram"
  [[params.capability]]  
      name = "Figma"
  [[params.capability]]  
      name = "Information Architecture"
  [[params.capability]]  
      name = "Wireframing"
  [[params.capability]]  
      name = "Prototyping"
  [[params.capability]]  
      name = "Fractional Leadership"
  [[params.capability]]  
      name = "creativity"

  [params.busuanzi_count]
    enable = true
    site_uv = true
    site_pv = true
    page_pv = true



# allow md file shows HTML format
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe= true
      hardWraps = false
      xhtml = false

# setup menu
sectionPagesMenu = "main"
[menu]
  [[menu.main]]
    name = "Work"
    url = "/#project"
    weight = 1
  [[menu.main]]
    name = "Abouts"
    identifier = "about"
    url = "/#about"
    weight = 2

  [[menu.main]]
    name = "Contact"
    identifier = "contact"
    url = "/#contact"
    weight = 3

# code block buil-in tool
pygmentsUseClasses=true
pygmentsCodeFences=true

